version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - JWT_SECRET=change_this_secret_in_prod
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER=admin
      POSTGRES_PASSWORD=securepassword
      POSTGRES_DB=sportdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: